import { describe, it, expect, beforeEach, vi } from "vitest";

vi.mock("../../src/util/git.js", () => ({
  gitHeadSha: vi.fn().mockResolvedValue("no-git"),
  modifiedFilesWithHashes: vi.fn().mockResolvedValue([]),
}));

// #205 regression guard. `lyse init` is interactive top-to-bottom; wrapping
// runInit in a long-lived CLI `withSpinner` keeps redrawing over the "Proceed?"
// prompt and buries it forever. The invariant — never caught by a "completes in
// time" test because the hang is a visual overlay, not a deadlock — is that the
// init command must NOT call withSpinner. We mock it to throw if it ever does.
const withSpinnerSpy = vi.fn();
vi.mock("../../src/util/with-spinner.js", () => ({
  withSpinner: (...args: unknown[]) => {
    withSpinnerSpy(...args);
    throw new Error("init must not use withSpinner (regression #205)");
  },
}));

import { mkdtempSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { gitInit, gitCommitAll } from "../_helpers/git.js";
import { initCommand } from "../../src/cli.js";
import { VERSION } from "../../src/index.js";

let dir: string;
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "lyse-init-cmd-"));
  gitInit(dir);
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify({ name: "t", version: "1.0.0", dependencies: { react: "^18.0.0" } }),
  );
  writeFileSync(join(dir, "Sample.tsx"), "export const S = () => <div>x</div>;");
  gitCommitAll(dir, "init");
});

describe("init command — #205 regression", () => {
  it("does not wrap runInit in a CLI spinner, and writes .lyse.yaml", async () => {
    await initCommand.run!({
      args: { path: dir, yes: false, scaffold: false, "migrate-tokens": false, _: [] },
    } as never);
    expect(withSpinnerSpy).not.toHaveBeenCalled();
    expect(existsSync(join(dir, ".lyse.yaml"))).toBe(true);
  });

  it("stamps the real version in the generated .lyse.yaml header (#204)", async () => {
    await initCommand.run!({
      args: { path: dir, yes: true, scaffold: false, "migrate-tokens": false, _: [] },
    } as never);
    const yaml = readFileSync(join(dir, ".lyse.yaml"), "utf8");
    expect(yaml).toContain(`# Generated by Lyse ${VERSION}`);
    expect(yaml).not.toContain("Generated by Lyse 0.1.0");
  });
});
