import { describe, it, expect } from "vitest";
import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cli = join(__dirname, "../dist/cli.js");
const fixture = join(__dirname, "../fixtures/full-ds");

describe("agents-md → agents rename", () => {
  it("lyse agents command works (new canonical)", () => {
    const out = execSync(`node ${cli} agents ${fixture} --static-only`, { encoding: "utf8" });
    expect(out).toContain("# AGENTS.md");
    expect(out).toContain("Card"); // fixture imports Card from @acme/ui
  });

  it("lyse agents-md command still works as deprecated alias", () => {
    const out = execSync(`node ${cli} agents-md ${fixture} --static-only 2>&1`, { encoding: "utf8" });
    // Should contain the deprecation warning
    expect(out).toContain("WARNING");
    expect(out).toContain("deprecated");
    expect(out).toContain("agents");
    // And should still produce the AGENTS.md output
    expect(out).toContain("# AGENTS.md");
    expect(out).toContain("Card");
  });

  it("both commands accept the same args and produce equivalent output", () => {
    const tmp1 = `/tmp/agents-${Date.now()}.md`;
    const tmp2 = `/tmp/agents-md-${Date.now()}.md`;

    // Test agents command with --output
    execSync(`node ${cli} agents ${fixture} --static-only --output ${tmp1}`, { encoding: "utf8" });
    const output1 = require("fs").readFileSync(tmp1, "utf8");
    expect(output1).toContain("# AGENTS.md");

    // Test agents-md command with --output (stderr is redirected to /dev/null to ignore deprecation warning)
    execSync(`node ${cli} agents-md ${fixture} --static-only --output ${tmp2} 2>/dev/null`, { encoding: "utf8" });
    const output2 = require("fs").readFileSync(tmp2, "utf8");
    expect(output2).toContain("# AGENTS.md");

    // Both files should have equivalent structure (ignoring timestamps which vary)
    // Remove timestamp lines for comparison
    const normalize = (content: string) => content.replace(/^> Auto-generated by Lyse .*/m, "");
    expect(normalize(output1)).toBe(normalize(output2));
  });
});
