import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { readFileSync, mkdtempSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cli = join(__dirname, "../dist/cli.js");
const fixture = join(__dirname, "../fixtures/full-ds");

/** Run `node <cli> <args…>` with no shell; returns stdout + stderr combined. */
function runCli(args: string[]): string {
  const r = spawnSync("node", [cli, ...args], { encoding: "utf8" });
  return `${r.stdout ?? ""}${r.stderr ?? ""}`;
}

describe("agents-md → agents rename", () => {
  it("lyse agents command works (new canonical)", () => {
    const out = runCli(["agents", fixture, "--static-only"]);
    expect(out).toContain("# AGENTS.md");
    expect(out).toContain("Card"); // fixture imports Card from @acme/ui
  });

  it("lyse agents-md command still works as deprecated alias", () => {
    const out = runCli(["agents-md", fixture, "--static-only"]);
    // Should contain the deprecation warning
    expect(out).toContain("WARNING");
    expect(out).toContain("deprecated");
    expect(out).toContain("agents");
    // And should still produce the AGENTS.md output
    expect(out).toContain("# AGENTS.md");
    expect(out).toContain("Card");
  });

  it("both commands accept the same args and produce equivalent output", () => {
    const dir = mkdtempSync(join(tmpdir(), "lyse-agents-alias-"));
    const tmp1 = join(dir, "agents.md");
    const tmp2 = join(dir, "agents-md.md");

    runCli(["agents", fixture, "--static-only", "--output", tmp1]);
    const output1 = readFileSync(tmp1, "utf8");
    expect(output1).toContain("# AGENTS.md");

    runCli(["agents-md", fixture, "--static-only", "--output", tmp2]);
    const output2 = readFileSync(tmp2, "utf8");
    expect(output2).toContain("# AGENTS.md");

    // Both files should have equivalent structure (ignoring timestamps which vary).
    const normalize = (content: string) => content.replace(/^> Auto-generated by Lyse .*/m, "");
    expect(normalize(output1)).toBe(normalize(output2));
  });
});
