// 45 sub-axes, 1:1 mapped to the 45 shipped rules.
// Each sub-axis declares the scoring axis it reports under (6 total per
// AxisName in packages/core/src/types.ts: tokens, a11y, components, stories,
// ai-surface, ai-governance). Naming rules report under the components axis.
import type { SubAxisRecord } from "../types.js";

export const SUB_AXES: SubAxisRecord[] = [
  { id: "tokens.color", axis: "tokens", name: "Color tokens", status: "experimental", precisionMeasured: 0.4430379746835443, recallMeasured: 1, precisionWilsonLowerBound: 0.3386778751145434, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["tokens/no-hardcoded-color"], llmDriven: false },
  { id: "tokens.spacing", axis: "tokens", name: "Spacing tokens", status: "experimental", precisionMeasured: 0.2727272727272727, recallMeasured: 1, precisionWilsonLowerBound: 0.16346381623843378, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["tokens/no-hardcoded-spacing"], llmDriven: false },
  { id: "tokens.dtcg-conformance", axis: "tokens", name: "DTCG conformance", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["tokens/dtcg-conformance"], llmDriven: false, deterministicValidator: true },
  { id: "tokens.description-coverage", axis: "tokens", name: "Token description coverage", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["tokens/description-coverage"], llmDriven: false, deterministicValidator: true },
  { id: "tokens.deprecated-token-usage", axis: "tokens", name: "Deprecated-token aliasing ($deprecated)", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["tokens/deprecated-token-usage"], llmDriven: false, deterministicValidator: true },
  { id: "tokens.theme-modes", axis: "tokens", name: "Theme modes (light/dark)", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["tokens/theme-modes-present"], llmDriven: false, deterministicValidator: true },
  { id: "tokens.responsive-breakpoints", axis: "tokens", name: "Responsive breakpoint scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/responsive-breakpoints"], llmDriven: false },
  { id: "tokens.z-index", axis: "tokens", name: "Z-index token scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-z-index"], llmDriven: false },
  { id: "tokens.opacity", axis: "tokens", name: "Opacity token scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-opacity"], llmDriven: false },
  { id: "tokens.border-radius", axis: "tokens", name: "Radii token scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-border-radius"], llmDriven: false },
  { id: "tokens.border-width", axis: "tokens", name: "Border-width token scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-border-width"], llmDriven: false },
  { id: "tokens.motion", axis: "tokens", name: "Motion token scale (duration/easing)", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-motion"], llmDriven: false },
  { id: "tokens.shadow", axis: "tokens", name: "Shadow / elevation token scale", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-shadow"], llmDriven: false },
  { id: "tokens.typography", axis: "tokens", name: "Typography token scale (size/weight/letter-spacing)", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["tokens/no-hardcoded-typography"], llmDriven: false },
  { id: "a11y.essentials", axis: "a11y", name: "jsx-a11y essentials", status: "experimental", precisionMeasured: null, recallMeasured: 1, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["a11y/essentials"], llmDriven: false },
  { id: "a11y.prefers-reduced-motion", axis: "a11y", name: "prefers-reduced-motion compliance", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["a11y/prefers-reduced-motion"], llmDriven: false },
  { id: "a11y.focus-visible", axis: "a11y", name: "focus-visible adoption", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["a11y/focus-visible"], llmDriven: false },
  { id: "a11y.inclusive-language", axis: "a11y", name: "Inclusive language", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["a11y/inclusive-language"], llmDriven: false },
  { id: "components.native-shadows", axis: "components", name: "Native shadow elements", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["components/no-native-shadows"], llmDriven: false, deterministicValidator: true },
  { id: "components.no-icon-fonts", axis: "components", name: "Icon delivery (SVG over icon-font)", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: null, contributesToScore: false, ruleIds: ["components/no-icon-fonts"], llmDriven: false },
  { id: "components.contracts-strictness", axis: "components", name: "Component prop contract strictness", status: "experimental", precisionMeasured: null, recallMeasured: null, precisionWilsonLowerBound: null, recallWilsonLowerBound: null, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["components/contracts-strictness"], llmDriven: false },
  { id: "components.naming-component-pascalcase", axis: "components", name: "Component PascalCase", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9035813714055363, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["naming/component-pascalcase"], llmDriven: false, deterministicValidator: true },
  { id: "components.naming-hook-prefix", axis: "components", name: "Hook `use` prefix", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9035813714055363, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["naming/hook-prefix"], llmDriven: false, deterministicValidator: true },
  { id: "stories.coverage", axis: "stories", name: "Storybook coverage", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["stories/coverage"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.agents-md-quality", axis: "ai-surface", name: "AGENTS.md quality", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["ai-surface/agents-md-quality"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.component-manifest-json", axis: "ai-surface", name: "Component manifest JSON", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/component-manifest-json"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.ds-index-exported", axis: "ai-surface", name: "DS index export", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/ds-index-exported"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.mcp-config-present", axis: "ai-surface", name: "MCP config present", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/mcp-config-present"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.llms-txt-structure", axis: "ai-surface", name: "llms.txt structure", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/llms-txt-structure"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.shadcn-registry-valid", axis: "ai-surface", name: "shadcn registry validity", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/shadcn-registry-valid"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.agent-instruction-files", axis: "ai-surface", name: "Agent instruction files (Cursor / Claude)", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["ai-surface/agent-instruction-files"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.changelog-present", axis: "ai-surface", name: "Structured CHANGELOG (versioning)", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["versioning/changelog-present"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.semver-versioning", axis: "ai-surface", name: "Semver version (package.json)", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["versioning/semver-versioning"], llmDriven: false, deterministicValidator: true },
  { id: "ai-surface.migration-guide-present", axis: "ai-surface", name: "Migration / upgrade guide", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9035813714055363, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: true, ruleIds: ["versioning/migration-guide-present"], llmDriven: false, deterministicValidator: true },
  { id: "ai-governance.ai-tokens-reserved", axis: "ai-governance", name: "Reserved AI-marker tokens inventory", status: "experimental", precisionMeasured: null, recallMeasured: 0.5714285714285714, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.40857411143974914, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/ai-tokens-reserved"], llmDriven: false },
  { id: "ai-governance.ai-marker-component-present", axis: "ai-governance", name: "AI-marker component present", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["ai-governance/ai-marker-component-present"], llmDriven: false, deterministicValidator: true },
  { id: "ai-governance.explainability-affordance", axis: "ai-governance", name: "Explainability affordance", status: "experimental", precisionMeasured: null, recallMeasured: 1, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/explainability-affordance"], llmDriven: true },
  { id: "ai-governance.ai-token-requires-marker", axis: "ai-governance", name: "AI token requires co-located marker", status: "experimental", precisionMeasured: null, recallMeasured: 0.2, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.10042446473798625, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/ai-token-requires-marker"], llmDriven: false },
  { id: "ai-governance.ai-loading-error-states", axis: "ai-governance", name: "AI loading state & error state", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["ai-governance/ai-loading-error-states"], llmDriven: false, deterministicValidator: true },
  { id: "ai-governance.human-control-affordances", axis: "ai-governance", name: "Human-control affordances", status: "experimental", precisionMeasured: null, recallMeasured: 1, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/human-control-affordances"], llmDriven: true },
  { id: "ai-governance.ai-marker-anti-patterns", axis: "ai-governance", name: "AI-marker anti-patterns", status: "experimental", precisionMeasured: null, recallMeasured: 1, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/ai-marker-anti-patterns"], llmDriven: true },
  { id: "ai-governance.ai-content-live-region", axis: "ai-governance", name: "AI content live region", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["ai-governance/ai-content-live-region"], llmDriven: false, deterministicValidator: true },
  { id: "ai-governance.disclaimer-present", axis: "ai-governance", name: "AI disclaimer present", status: "experimental", precisionMeasured: null, recallMeasured: 1, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/disclaimer-present"], llmDriven: true },
  { id: "ai-governance.feedback-control-present", axis: "ai-governance", name: "AI feedback control present", status: "stable", precisionMeasured: 1, recallMeasured: 1, precisionWilsonLowerBound: 0.9010990076755959, recallWilsonLowerBound: 0.9010990076755959, lastCalibrated: "2026-06-17T00:00:00.000Z", contributesToScore: true, ruleIds: ["ai-governance/feedback-control-present"], llmDriven: false, deterministicValidator: true },
  { id: "ai-governance.value-gate-doc-present", axis: "ai-governance", name: "AI value-gate governance doc", status: "experimental", precisionMeasured: null, recallMeasured: 0.8, precisionWilsonLowerBound: null, recallWilsonLowerBound: 0.6410838693433439, lastCalibrated: "2026-06-15T16:54:07.177Z", contributesToScore: false, ruleIds: ["ai-governance/value-gate-doc-present"], llmDriven: true },
];

export function getSubAxis(id: string): SubAxisRecord | undefined {
  return SUB_AXES.find((s) => s.id === id);
}
