import type {
  DsManifest,
  ManifestComponent,
  ManifestExtractionEntry,
  ManifestProp,
  ManifestToken,
} from "../manifest/types.js";
import type { AuditResult } from "../types.js";

const MAX_TOKENS_PER_AXIS = 40;
const MAX_COMPONENTS = 40;

function moreLine(rest: number): string {
  return `- … and ${rest} more — run \`lyse manifest\` for the full set.`;
}

function groupTokensByAxis(tokens: ManifestToken[]): Map<ManifestToken["axis"], ManifestToken[]> {
  const groups = new Map<ManifestToken["axis"], ManifestToken[]>();
  for (const token of tokens) {
    const group = groups.get(token.axis);
    if (group) {
      group.push(token);
    } else {
      groups.set(token.axis, [token]);
    }
  }
  return groups;
}

function renderProp(prop: ManifestProp): string {
  const parts = [`\`${prop.name}\`: \`${prop.type ?? "unknown"}\``];
  if (prop.optional) parts.push("optional");
  if (prop.default !== null) parts.push(`default: \`${prop.default}\``);
  if (prop.variants !== null && prop.variants.length > 0) {
    parts.push(`variants: ${prop.variants.map((v) => `\`${v}\``).join(", ")}`);
  }
  return `  - ${parts.join(" — ")}`;
}

function renderComponentBlock(component: ManifestComponent): string[] {
  const lines = [
    `### ${component.name}`,
    `- Module: \`${component.module}\``,
    `- File: \`${component.file ?? "unknown"}\``,
    `- Design system component: ${component.isDesignSystem ? "yes" : "no"}`,
    `- Detection: \`${component.detection}\``,
    `- Usage count: ${component.usageCount}`,
    `- Stories: ${component.storyCount}`,
  ];
  if (component.props.length === 0) {
    lines.push(`- Props: none documented`);
  } else {
    lines.push(`- Props:`);
    lines.push(...component.props.map(renderProp));
  }
  return lines;
}

function renderExtractionWarnings(entries: ManifestExtractionEntry[]): string[] {
  const unhealthy = entries.filter((e) => e.status === "degraded" || e.status === "failed");
  if (unhealthy.length === 0) return [];
  const lines = [`## Extraction warnings`, ``];
  for (const entry of unhealthy) {
    const remediation = entry.remediation !== null ? ` — ${entry.remediation}` : "";
    lines.push(`- **${entry.extractor}**: ${entry.status}${remediation}`);
  }
  lines.push(``);
  return lines;
}

export function renderAgentsMd(manifest: DsManifest, result: AuditResult): string {
  return [
    `# AGENTS.md — Design System Contract`,
    ``,
    `> Auto-generated by Lyse v${result.toolVersion} on ${result.timestamp}.`,
    `> Token set: \`${manifest.tokenSetHash}\``,
    `> Do not hand-edit; re-run \`lyse audit\` to refresh.`,
    ``,
    ...renderExtractionWarnings(manifest.extraction.entries),
    ...renderStackSection(result.stack),
    ...renderTokensSection(manifest.tokens),
    ...renderComponentsSection(manifest.components),
    `## 4. Hard rules for AI-generated code`,
    `- Never use hardcoded colors. Always use one of the concrete tokens listed above.`,
    `- Never use native \`<button>\`, \`<input>\`, \`<select>\`, \`<textarea>\`, \`<a>\` when a DS equivalent exists.`,
    `- Always include \`alt\` on \`<img>\`, \`aria-label\` on icon-only buttons.`,
    `- Always ship a Storybook story with new DS components.`,
    ``,
    `## 5. Lyse contract`,
    `Scoring: \`${result.scoringVersion}\``,
    ``,
    "```",
    `schema: 1`,
    `rules_version: ${result.rulesVersion}`,
    `tool_version: ${result.toolVersion}`,
    `scoring_version: ${result.scoringVersion}`,
    `token_set_hash: ${manifest.tokenSetHash}`,
    `schema_version: ${manifest.schemaVersion}`,
    "```",
    ``,
  ].join("\n");
}

function renderStackSection(stack: string[]): string[] {
  const lines = [`## 1. Stack detected`];
  if (stack.length === 0) {
    lines.push(`None detected.`);
  } else {
    lines.push(...stack.map((s) => `- ${s}`));
  }
  lines.push(``);
  return lines;
}

function renderTokensSection(tokens: ManifestToken[]): string[] {
  const lines = [`## 2. Design tokens`, ``];
  if (tokens.length === 0) {
    lines.push(`None detected.`, ``);
    return lines;
  }
  for (const [axis, group] of groupTokensByAxis(tokens)) {
    lines.push(`### ${axis}`);
    const shown = group.slice(0, MAX_TOKENS_PER_AXIS);
    lines.push(...shown.map((t) => `- \`${t.id}\` → \`${t.value}\``));
    const rest = group.length - shown.length;
    if (rest > 0) lines.push(moreLine(rest));
    lines.push(``);
  }
  return lines;
}

function renderComponentsSection(components: ManifestComponent[]): string[] {
  const lines = [`## 3. Component contracts`, ``];
  if (components.length === 0) {
    lines.push(`None detected.`, ``);
    return lines;
  }
  const shown = components.slice(0, MAX_COMPONENTS);
  for (const component of shown) {
    lines.push(...renderComponentBlock(component), ``);
  }
  const rest = components.length - shown.length;
  if (rest > 0) lines.push(moreLine(rest), ``);
  return lines;
}
