import type { AuditResult } from "../types.js";

interface MdContext { tokenNamespaces: string[]; components: string[] }

export function renderAgentsMd(result: AuditResult, mdCtx: MdContext): string {
  return [
    `# AGENTS.md — Design System Contract`,
    ``,
    `> Auto-generated by Lyse v${result.toolVersion} on ${result.timestamp}.`,
    `> Do not hand-edit; re-run \`lyse audit\` to refresh.`,
    ``,
    `## 1. Stack detected`,
    ...result.stack.map((s) => `- ${s}`),
    ``,
    `## 2. Component inventory`,
    ...mdCtx.components.map((c) => `- \`${c}\``),
    ``,
    `## 3. Token namespaces`,
    ...mdCtx.tokenNamespaces.map((n) => `- \`${n}\``),
    ``,
    `## 4. Hard rules for AI-generated code`,
    `- Never use hardcoded colors. Always use a token from the namespaces above.`,
    `- Never use native \`<button>\`, \`<input>\`, \`<select>\`, \`<textarea>\`, \`<a>\` when a DS equivalent exists.`,
    `- Always include \`alt\` on \`<img>\`, \`aria-label\` on icon-only buttons.`,
    `- Always ship a Storybook story with new DS components.`,
    ``,
    `## 5. Lyse contract`,
    `Scoring: \`${result.scoringVersion}\``,
    ``,
    `\`\`\``,
    `schema: 1`,
    `rules_version: ${result.rulesVersion}`,
    `tool_version: ${result.toolVersion}`,
    `scoring_version: ${result.scoringVersion}`,
    `\`\`\``,
    ``,
  ].join("\n");
}

