import { join } from "node:path";
import fg from "fast-glob";
import type {
  Rule,
  RuleContext,
  ParsedFiles,
  RuleEvalResult,
  Finding,
} from "../types.js";
import { createLyseRule } from "./_rule-module.js";
import {
  isAiMarkerName,
  extractNamesFromSource,
  safeReadText,
  COMPONENT_GLOB,
  SCAN_IGNORE,
  makeAllowlistCheck,
} from "./ai-governance-ai-marker-component-present.js";
import {
  aiNounAlternation,
  makeLocaleMatcher,
  type LocaleMatcher,
} from "./_i18n-vocabulary.js";

const RULE_ID = "ai-governance/ai-marker-anti-patterns";
const DISABLE_DIRECTIVE = `lyse-disable ${RULE_ID}`;
const ALLOWLIST_CANDIDATES = [
  "README.md",
  "README",
  "README.mdx",
  "readme.md",
  ".lyse.yaml",
  ".lyse.yml",
];

const isAllowlisted = makeAllowlistCheck(DISABLE_DIRECTIVE);

const SPARKLE_LITERAL = /[✨✩\u{1F31F}❇]/u;
const SPARKLE_IMPORT = /\b(Sparkle|Sparkles|SparkleIcon)\b/;
const SPARKLE_ICON_PROP = /icon\s*=\s*["'`]\s*sparkle/i;
const TEXT_MARKER_COMPOUND = /\b(generated by ai|ai[- ]generated|powered by ai)\b/i;
const CTA_STRIP = /<(?:button|Button|a)\b[^>]*>[\s\S]*?<\/(?:button|Button|a)\s*>|<[A-Za-z][\w.-]*\b[^>]*\brole\s*=\s*["']button["'][^>]*>[\s\S]*?<\/[A-Za-z][\w.-]*\s*>/g;

// Uppercased Latin nouns matched case-sensitively (AI/IA/KI) to preserve the
// original "standalone uppercase AI" precision; explicit non-letter boundary
// instead of `\b` because CJK nouns (人工知能) have no Latin word boundary —
// their neighbors are never [A-Za-z], so the same class works for both.
const standaloneNounReCache = new Map<string, RegExp>();

function standaloneAiNounRe(repoRoot: string): RegExp {
  let re = standaloneNounReCache.get(repoRoot);
  if (!re) {
    re = new RegExp(
      `(?:^|[^A-Za-z])(?:${aiNounAlternation(repoRoot).toUpperCase()})(?:[^A-Za-z]|$)`,
    );
    standaloneNounReCache.set(repoRoot, re);
  }
  return re;
}

const disclaimerMatcherCache = new Map<string, LocaleMatcher>();

function disclaimerMatcher(repoRoot: string): LocaleMatcher {
  let matcher = disclaimerMatcherCache.get(repoRoot);
  if (!matcher) {
    matcher = makeLocaleMatcher("disclaimerPhrases", repoRoot);
    disclaimerMatcherCache.set(repoRoot, matcher);
  }
  return matcher;
}

export function detectSparkleOnlyMarker(source: string, repoRoot = ""): boolean {
  const hasSparkle =
    SPARKLE_LITERAL.test(source) ||
    SPARKLE_IMPORT.test(source) ||
    SPARKLE_ICON_PROP.test(source);
  if (!hasSparkle) return false;
  if (TEXT_MARKER_COMPOUND.test(source)) return false;
  if (disclaimerMatcher(repoRoot).matchesPhrase(source)) return false;
  const stripped = source.replace(CTA_STRIP, " ");
  if (standaloneAiNounRe(repoRoot).test(stripped)) return false;
  for (const tag of source.matchAll(/<\s*([A-Za-z][\w.-]*)/g)) {
    if (tag[1] !== undefined && isAiMarkerName(tag[1], repoRoot)) return false;
  }
  return true;
}

export function fileHasAiContext(source: string, repoRoot = ""): boolean {
  for (const name of extractNamesFromSource(source)) {
    if (isAiMarkerName(name, repoRoot)) return true;
  }
  for (const tag of source.matchAll(/<\s*([A-Za-z][\w.-]*)/g)) {
    if (tag[1] !== undefined && isAiMarkerName(tag[1], repoRoot)) return true;
  }
  return false;
}

const CTA_OPEN = /<(button|Button|a)\b[^>]*>|<[A-Za-z][\w.-]*\b[^>]*\brole\s*=\s*["']button["'][^>]*>/g;

export function detectAiInCtaLabel(
  source: string,
  repoRoot = "",
): { label: string }[] {
  const out: { label: string }[] = [];
  let m: RegExpExecArray | null;
  CTA_OPEN.lastIndex = 0;
  while ((m = CTA_OPEN.exec(source)) !== null) {
    const openTag = m[0];
    const tagNameMatch = /^<([A-Za-z][\w.-]*)/.exec(openTag);
    const tagName = tagNameMatch?.[1] ?? "div";
    const rest = source.slice(m.index + openTag.length);
    const closeRe = new RegExp(`<\\/\\s*${tagName}\\s*>`);
    const close = rest.search(closeRe);
    const inner = (close === -1 ? rest : rest.slice(0, close))
      .replace(/<[^>]*>/g, " ")
      .trim();
    if (inner.length > 0 && standaloneAiNounRe(repoRoot).test(inner)) {
      out.push({ label: inner.replace(/\s+/g, " ") });
    }
  }
  return out;
}

const evaluate = async (
  ctx: RuleContext,
  _files: ParsedFiles,
): Promise<RuleEvalResult> => {
  const findings: Finding[] = [];
  if (!ctx.repoRoot) {
    return { findings, opportunities: 0 };
  }
  if (isAllowlisted(ctx.repoRoot)) {
    return { findings, opportunities: 0 };
  }

  let componentFiles: string[] = [];
  try {
    componentFiles = fg
      .sync(COMPONENT_GLOB, {
        cwd: ctx.repoRoot,
        ignore: SCAN_IGNORE,
        absolute: false,
        dot: false,
        onlyFiles: true,
        unique: true,
      })
      .sort();
  } catch {
    // non-fatal
  }

  for (const rel of componentFiles) {
    const source = safeReadText(join(ctx.repoRoot, rel));
    if (!source) continue;

    if (
      fileHasAiContext(source, ctx.repoRoot) &&
      detectSparkleOnlyMarker(source, ctx.repoRoot)
    ) {
      findings.push({
        ruleId: RULE_ID,
        axis: "ai-governance",
        severity: "warning",
        location: { file: rel, line: 1, column: 1 },
        message:
          "Sparkle used as the sole AI marker — pair it with a text label or AI-marker component (SAP Fiori XAI forbids icon-only AI marking).",
      });
    }

    for (const hit of detectAiInCtaLabel(source, ctx.repoRoot)) {
      findings.push({
        ruleId: RULE_ID,
        axis: "ai-governance",
        severity: "warning",
        location: { file: rel, line: 1, column: 1 },
        message: `"AI" used as a CTA action label ("${hit.label}") — describe the action, not the technology (GitLab Pajamas).`,
      });
    }
  }

  findings.sort((a, b) => {
    const fa = a.location?.file ?? "";
    const fb = b.location?.file ?? "";
    if (fa < fb) return -1;
    if (fa > fb) return 1;
    return (a.location?.line ?? 0) - (b.location?.line ?? 0);
  });

  return { findings, opportunities: componentFiles.length };
};

export const rule: Rule = createLyseRule({
  meta: {
    axis: "ai-governance",
    lyseRuleId: RULE_ID,
    defaultSeverity: "warning",
    shortDescription: "Lint AI-marker anti-patterns in component source files",
    fullDescription:
      "Scans component files (`**/*.{tsx,jsx,vue}`) for two forbidden AI-marking anti-patterns. Anti-pattern A: a sparkle signal (`✨` literal, `Sparkle`/`Sparkles`/`SparkleIcon` import, or `icon=\"sparkle*\"` prop) used as the sole AI marker with no accompanying text label or AI-marker component — SAP Fiori XAI forbids icon-only marking because it fails accessibility and is ambiguous. Anti-pattern B: a standalone, case-sensitive AI noun from any active locale (`AI`, `IA`, `KI`, `人工知能`, …) used as the primary action label of a `<button>`, `<Button>`, or `<a>` element — GitLab Pajamas forbids this because the noun describes the technology, not the user action. Both detectors are pure source heuristics with no runtime or behavioral analysis. Emits `warning` for each occurrence. A sparkle accompanied by a text AI-marker (including localized disclaimers such as `Généré par IA`) or AI-marker component (`AILabel`, `BadgeIA`, `AIBadge`, magic-* etc.) is not flagged. AI nouns appearing only in body or descriptor text (headings, paragraphs) are not flagged.",
    helpUri:
      "https://github.com/lyse-labs/lyse/blob/main/docs/rules/ai-governance-ai-marker-anti-patterns.md",
    rationale: `Why it matters

Icon-only AI marking (a lone sparkle ✨) silently fails users who rely on assistive technology: a screen reader announces an image description or nothing at all — not "AI-generated." SAP Fiori XAI made this explicit: sparkle MUST be paired with a text label or dedicated AI-marker component. Lyse enforces the same constraint statically.

Labelling a CTA button "AI" is a UX anti-pattern: "AI" is a noun describing technology, not an action verb. GitLab Pajamas explicitly forbids it, recommending "Summarize," "Explain," or "Generate" instead — words that tell the user what will happen, not what engine does it. Lyse catches this in source before it ships.

Both findings are warnings (not errors) because the fix is mechanical and low-risk.`,
    examples: [
      {
        good: '<span><AILabel>AI</AILabel> <Sparkles aria-hidden/></span>',
        bad: '<span>✨ {generatedText}</span>',
      },
      {
        good: '<button>Summarize</button>',
        bad: '<button>AI</button>',
      },
      {
        good: '<button>Draft reply</button>',
        bad: '<button>Ask AI</button>',
      },
    ],
    allowlist: [
      "repos containing `lyse-disable ai-governance/ai-marker-anti-patterns` in an adjacent README or `.lyse.yaml` — rule is N/A for the entire repo",
      "files larger than 1 MB — skipped to avoid pathological cases",
      "files under `node_modules/`, `dist/`, `build/`",
      "sparkle accompanied by a text AI-marker (`AILabel`, `AIBadge`, magic-*, GenAI*, etc.) — not flagged",
      "`AI` in non-CTA elements (headings, paragraphs, spans) — not flagged",
    ],
  },
  defaultOptions: [],
  create: () => ({ evaluate }),
});

export const _internal = {
  detectSparkleOnlyMarker,
  detectAiInCtaLabel,
  fileHasAiContext,
  isAllowlisted,
  DISABLE_DIRECTIVE,
  ALLOWLIST_CANDIDATES,
};
