import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import fg from "fast-glob";
import type {
  Rule,
  RuleContext,
  ParsedFiles,
  RuleEvalResult,
  Finding,
} from "../types.js";
import { createLyseRule } from "./_rule-module.js";
import {
  isAiMarkerName,
  safeReadText,
} from "./ai-governance-ai-marker-component-present.js";

const RULE_ID = "ai-governance/ai-marker-anti-patterns";
const MAX_ALLOWLIST_FILE_BYTES = 1_000_000;
const DISABLE_DIRECTIVE = `lyse-disable ${RULE_ID}`;

const ALLOWLIST_CANDIDATES = [
  "README.md",
  "README",
  "README.mdx",
  "readme.md",
  ".lyse.yaml",
  ".lyse.yml",
];

function isAllowlisted(repoRoot: string): boolean {
  for (const candidate of ALLOWLIST_CANDIDATES) {
    const abs = join(repoRoot, candidate);
    if (!existsSync(abs)) continue;
    try {
      const stat = statSync(abs);
      if (!stat.isFile() || stat.size > MAX_ALLOWLIST_FILE_BYTES) continue;
      const raw = readFileSync(abs, "utf8");
      if (raw.includes(DISABLE_DIRECTIVE)) return true;
    } catch {
      // unreadable — fall through
    }
  }
  return false;
}

const SPARKLE_LITERAL = /[✨✩\u{1F31F}❇]/u;
const SPARKLE_IMPORT = /\b(Sparkle|Sparkles|SparkleIcon)\b/;
const SPARKLE_ICON_PROP = /icon\s*=\s*["'`]\s*sparkle/i;
const TEXT_MARKER_COMPOUND = /\b(generated by ai|ai[- ]generated|powered by ai)\b/i;
const TEXT_MARKER_STANDALONE = /(^|[^A-Za-z])AI([^A-Za-z]|$)/;
const CTA_STRIP = /<(?:button|Button|a)\b[^>]*>[\s\S]*?<\/(?:button|Button|a)\s*>|<[A-Za-z][\w.-]*\b[^>]*\brole\s*=\s*["']button["'][^>]*>[\s\S]*?<\/[A-Za-z][\w.-]*\s*>/g;

export function detectSparkleOnlyMarker(source: string): boolean {
  const hasSparkle =
    SPARKLE_LITERAL.test(source) ||
    SPARKLE_IMPORT.test(source) ||
    SPARKLE_ICON_PROP.test(source);
  if (!hasSparkle) return false;
  if (TEXT_MARKER_COMPOUND.test(source)) return false;
  const stripped = source.replace(CTA_STRIP, " ");
  if (TEXT_MARKER_STANDALONE.test(stripped)) return false;
  for (const tag of source.matchAll(/<\s*([A-Za-z][\w.-]*)/g)) {
    if (tag[1] !== undefined && isAiMarkerName(tag[1])) return false;
  }
  return true;
}

const CTA_OPEN = /<(button|Button|a)\b[^>]*>|<[A-Za-z][\w.-]*\b[^>]*\brole\s*=\s*["']button["'][^>]*>/g;
const STANDALONE_AI = /(^|[^A-Za-z])AI([^A-Za-z]|$)/;

export function detectAiInCtaLabel(source: string): { label: string }[] {
  const out: { label: string }[] = [];
  let m: RegExpExecArray | null;
  CTA_OPEN.lastIndex = 0;
  while ((m = CTA_OPEN.exec(source)) !== null) {
    const openTag = m[0];
    const tagNameMatch = /^<([A-Za-z][\w.-]*)/.exec(openTag);
    const tagName = tagNameMatch?.[1] ?? "div";
    const rest = source.slice(m.index + openTag.length);
    const closeRe = new RegExp(`<\\/\\s*${tagName}\\s*>`);
    const close = rest.search(closeRe);
    const inner = (close === -1 ? rest : rest.slice(0, close))
      .replace(/<[^>]*>/g, " ")
      .trim();
    if (inner.length > 0 && STANDALONE_AI.test(inner)) {
      out.push({ label: inner.replace(/\s+/g, " ") });
    }
  }
  return out;
}

const evaluate = async (
  ctx: RuleContext,
  _files: ParsedFiles,
): Promise<RuleEvalResult> => {
  const findings: Finding[] = [];
  if (!ctx.repoRoot) {
    return { findings, opportunities: 0 };
  }
  if (isAllowlisted(ctx.repoRoot)) {
    return { findings, opportunities: 0 };
  }

  let componentFiles: string[] = [];
  try {
    componentFiles = fg
      .sync("**/*.{tsx,jsx,vue}", {
        cwd: ctx.repoRoot,
        ignore: ["**/node_modules/**", "**/dist/**", "**/build/**"],
        absolute: false,
        onlyFiles: true,
        unique: true,
      })
      .sort();
  } catch {
    // non-fatal
  }

  for (const rel of componentFiles) {
    const source = safeReadText(join(ctx.repoRoot, rel));
    if (!source) continue;

    if (detectSparkleOnlyMarker(source)) {
      findings.push({
        ruleId: RULE_ID,
        axis: "ai-governance",
        severity: "warning",
        location: { file: rel, line: 1, column: 1 },
        message:
          "Sparkle used as the sole AI marker — pair it with a text label or AI-marker component (SAP Fiori XAI forbids icon-only AI marking).",
      });
    }

    for (const hit of detectAiInCtaLabel(source)) {
      findings.push({
        ruleId: RULE_ID,
        axis: "ai-governance",
        severity: "warning",
        location: { file: rel, line: 1, column: 1 },
        message: `"AI" used as a CTA action label ("${hit.label}") — describe the action, not the technology (GitLab Pajamas).`,
      });
    }
  }

  findings.sort((a, b) => {
    const fa = a.location?.file ?? "";
    const fb = b.location?.file ?? "";
    if (fa < fb) return -1;
    if (fa > fb) return 1;
    return (a.location?.line ?? 0) - (b.location?.line ?? 0);
  });

  return { findings, opportunities: componentFiles.length };
};

export const rule: Rule = createLyseRule({
  meta: {
    axis: "ai-governance",
    lyseRuleId: RULE_ID,
    defaultSeverity: "warning",
    shortDescription: "Lint AI-marker anti-patterns in component source files",
    fullDescription:
      "Scans component files (`**/*.{tsx,jsx,vue}`) for two forbidden AI-marking anti-patterns. Anti-pattern A: a sparkle signal (`✨` literal, `Sparkle`/`Sparkles`/`SparkleIcon` import, or `icon=\"sparkle*\"` prop) used as the sole AI marker with no accompanying text label or AI-marker component — SAP Fiori XAI forbids icon-only marking because it fails accessibility and is ambiguous. Anti-pattern B: the standalone, case-sensitive token `AI` used as the primary action label of a `<button>`, `<Button>`, or `<a>` element — GitLab Pajamas forbids this because `AI` describes the technology, not the user action. Both detectors are pure source heuristics with no runtime or behavioral analysis. Emits `warning` for each occurrence. A sparkle accompanied by a text AI-marker or AI-marker component (`AILabel`, `AIBadge`, magic-* etc.) is not flagged. `AI` appearing only in body or descriptor text (headings, paragraphs) is not flagged.",
    helpUri:
      "https://github.com/lyse-labs/lyse/blob/main/docs/rules/ai-governance-ai-marker-anti-patterns.md",
    rationale: `Why it matters

Icon-only AI marking (a lone sparkle ✨) silently fails users who rely on assistive technology: a screen reader announces an image description or nothing at all — not "AI-generated." SAP Fiori XAI made this explicit: sparkle MUST be paired with a text label or dedicated AI-marker component. Lyse enforces the same constraint statically.

Labelling a CTA button "AI" is a UX anti-pattern: "AI" is a noun describing technology, not an action verb. GitLab Pajamas explicitly forbids it, recommending "Summarize," "Explain," or "Generate" instead — words that tell the user what will happen, not what engine does it. Lyse catches this in source before it ships.

Both findings are warnings (not errors) because the fix is mechanical and low-risk.`,
    examples: [
      {
        good: '<span><AILabel>AI</AILabel> <Sparkles aria-hidden/></span>',
        bad: '<span>✨ {generatedText}</span>',
      },
      {
        good: '<button>Summarize</button>',
        bad: '<button>AI</button>',
      },
      {
        good: '<button>Draft reply</button>',
        bad: '<button>Ask AI</button>',
      },
    ],
    allowlist: [
      "repos containing `lyse-disable ai-governance/ai-marker-anti-patterns` in an adjacent README or `.lyse.yaml` — rule is N/A for the entire repo",
      "files larger than 1 MB — skipped to avoid pathological cases",
      "files under `node_modules/`, `dist/`, `build/`",
      "sparkle accompanied by a text AI-marker (`AILabel`, `AIBadge`, magic-*, GenAI*, etc.) — not flagged",
      "`AI` in non-CTA elements (headings, paragraphs, spans) — not flagged",
    ],
  },
  defaultOptions: [],
  create: () => ({ evaluate }),
});

export const _internal = {
  detectSparkleOnlyMarker,
  detectAiInCtaLabel,
  isAllowlisted,
  DISABLE_DIRECTIVE,
  ALLOWLIST_CANDIDATES,
};
