// packages/core/src/rules/pack-loader.ts
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import type { Rule } from '../types.js';
import { getTemplate } from './templates/registry.js';
import { ruleMap } from './registry.js';

// Inlined from the moved llm/types.ts. The generated rule pack is the file
// `.lyse/generated-rules.yaml` produced by v0.2+'s LLM-rule-pack path; the
// schema is preserved here so the loader can still consume packs authored
// elsewhere (e.g. checked in, or generated by a future experimental flow).
export interface RulePack {
  version: 1;
  generated_at: string;
  generated_by: string;
  generated_from: {
    lyse_version: string;
    template_catalog_version: number;
    deps_hash: string;
    files_hash: string;
  };
  rules: Array<{
    id: string;
    template: string;
    axis: 'tokens' | 'a11y' | 'components' | 'stories';
    severity: 'error' | 'warning' | 'info' | 'off';
    config: Record<string, unknown>;
    metadata?: { description?: string; auto_fixable?: boolean; learn_url?: string | null };
  }>;
}

export interface LoadResult {
  rules: Rule[];
  warnings: string[];
  pack?: RulePack;
}

export function loadGeneratedPack(repoRoot: string): LoadResult {
  const packPath = join(repoRoot, '.lyse', 'generated-rules.yaml');
  if (!existsSync(packPath)) {
    return { rules: [], warnings: [] };
  }
  const raw = readFileSync(packPath, 'utf8');
  let pack: RulePack;
  try {
    pack = parseYaml(raw) as RulePack;
  } catch (err) {
    return { rules: [], warnings: [`Failed to parse .lyse/generated-rules.yaml: ${(err as Error).message}`] };
  }
  if (pack?.version !== 1) {
    return { rules: [], warnings: [`Unsupported pack version: ${pack?.version}`] };
  }
  const rules: Rule[] = [];
  const warnings: string[] = [];
  const seenIds = new Set<string>();
  for (const r of pack.rules ?? []) {
    if (r.severity === 'off') {
      // explicit off — skip rule entirely, no findings
      continue;
    }
    if (ruleMap.has(r.id)) {
      warnings.push(`Generated rule id "${r.id}" collides with a built-in rule — skipped (built-in wins)`);
      continue;
    }
    if (seenIds.has(r.id)) {
      warnings.push(`Duplicate rule id "${r.id}" skipped`);
      continue;
    }
    seenIds.add(r.id);
    const template = getTemplate(r.template);
    if (!template) {
      warnings.push(`Unknown template "${r.template}" for rule "${r.id}" — skipped`);
      continue;
    }
    try {
      const rule = template.build({
        ruleId: r.id,
        axis: r.axis,
        severity: r.severity,
        config: r.config,
      });
      rules.push(rule);
    } catch (err) {
      warnings.push(`Failed to build rule "${r.id}" from template "${r.template}": ${(err as Error).message}`);
    }
  }
  return { rules, warnings, pack };
}
