import { describe, it, expect } from "vitest";
import { parseFileOverrides } from "../../src/suppression/frontmatter.js";

const block = (body: string) => `/**\n * @lyse-overrides\n${body} */\nimport React from "react";\n`;

describe("parseFileOverrides", () => {
  it("returns empty when no @lyse-overrides block is present", () => {
    const o = parseFileOverrides('import React from "react";\nconst x = "#fff";');
    expect(o.off.size).toBe(0);
    expect(o.severity.size).toBe(0);
  });

  it("parses an `off` entry into the off set", () => {
    const o = parseFileOverrides(block(" *   stories/coverage: off\n"));
    expect(o.off.has("stories/coverage")).toBe(true);
    expect(o.severity.size).toBe(0);
  });

  it("parses a real severity into the severity map", () => {
    const o = parseFileOverrides(block(" *   tokens/no-hardcoded-color: error\n"));
    expect(o.severity.get("tokens/no-hardcoded-color")).toBe("error");
    expect(o.off.size).toBe(0);
  });

  it("parses multiple entries (mixed off + severity)", () => {
    const o = parseFileOverrides(
      block(" *   tokens/no-hardcoded-color: error\n *   stories/coverage: off\n"),
    );
    expect(o.severity.get("tokens/no-hardcoded-color")).toBe("error");
    expect(o.off.has("stories/coverage")).toBe(true);
  });

  it("stops parsing at the first non-entry comment line", () => {
    const o = parseFileOverrides(
      block(" *   tokens/no-hardcoded-color: error\n * some prose\n *   a11y/essentials: off\n"),
    );
    expect(o.severity.get("tokens/no-hardcoded-color")).toBe("error");
    expect(o.off.has("a11y/essentials")).toBe(false);
  });

  it("ignores an invalid severity value", () => {
    const o = parseFileOverrides(block(" *   tokens/no-hardcoded-color: critical\n"));
    expect(o.severity.size).toBe(0);
    expect(o.off.size).toBe(0);
  });

  it("parses every entry of the exact issue-226 CSS block", () => {
    const css = `/**
 * @lyse-overrides
 *   tokens/no-hardcoded-color: off
 *   tokens/no-hardcoded-typography: off
 *   tokens/no-hardcoded-opacity: off
 *   tokens/no-hardcoded-motion: off
 */
/* -------------------------------------------
 *  Autogenerated by Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

:root {
  --core-blue-10: oklch(0.97 0.01 255) /* #EFF6FF */;
}
`;
    const o = parseFileOverrides(css);
    expect([...o.off].sort()).toEqual([
      "tokens/no-hardcoded-color",
      "tokens/no-hardcoded-motion",
      "tokens/no-hardcoded-opacity",
      "tokens/no-hardcoded-typography",
    ]);
  });

  it("parses a CRLF file identically to an LF file (#226)", () => {
    const lf = block(" *   tokens/no-hardcoded-color: off\n *   stories/coverage: off\n");
    const o = parseFileOverrides(lf.replace(/\n/g, "\r\n"));
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("stories/coverage")).toBe(true);
  });

  it("tolerates blank comment continuation lines between entries (#226)", () => {
    const o = parseFileOverrides(
      block(" *\n *   tokens/no-hardcoded-color: off\n *\n *   stories/coverage: off\n"),
    );
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("stories/coverage")).toBe(true);
  });

  it("parses an entry on the same line as the tag (#226)", () => {
    const o = parseFileOverrides("/** @lyse-overrides tokens/no-hardcoded-color: off */\n");
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
  });

  it("parses multiple @lyse-overrides blocks in one file (#226)", () => {
    const src =
      "/**\n * @lyse-overrides\n *   tokens/no-hardcoded-color: off\n */\n" +
      "const a = 1;\n" +
      "/**\n * @lyse-overrides\n *   stories/coverage: off\n *   a11y/essentials: error\n */\n";
    const o = parseFileOverrides(src);
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("stories/coverage")).toBe(true);
    expect(o.severity.get("a11y/essentials")).toBe("error");
  });

  it("repeated per-line tag form parses each tagged entry (#226)", () => {
    const src =
      "/**\n" +
      " * @lyse-overrides tokens/no-hardcoded-color: off\n" +
      " * @lyse-overrides tokens/no-hardcoded-typography: off\n" +
      " */\n";
    const o = parseFileOverrides(src);
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("tokens/no-hardcoded-typography")).toBe(true);
  });

  it("tolerates a decorative separator line between entries", () => {
    const o = parseFileOverrides(
      block(" *   tokens/no-hardcoded-color: off\n * ----------\n *   stories/coverage: off\n"),
    );
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("stories/coverage")).toBe(true);
  });

  it("a tag quoted in code or prose never activates overrides", () => {
    const inString =
      'const help = "add @lyse-overrides tokens/no-hardcoded-color: off to a JSDoc block";\n' +
      "tokens/no-hardcoded-color: off\n";
    expect(parseFileOverrides(inString).off.size).toBe(0);

    const inProse =
      "/**\n * To disable a rule, use @lyse-overrides in a comment.\n *   tokens/no-hardcoded-color: off\n */\n";
    expect(parseFileOverrides(inProse).off.size).toBe(0);
  });

  it("does not read past the end of the comment block", () => {
    const src =
      "/**\n * @lyse-overrides\n *   tokens/no-hardcoded-color: off\n */\n" +
      "tokens/no-hardcoded-spacing: off\n";
    const o = parseFileOverrides(src);
    expect(o.off.has("tokens/no-hardcoded-color")).toBe(true);
    expect(o.off.has("tokens/no-hardcoded-spacing")).toBe(false);
  });
});
