import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  BUILTIN_LOCALES,
  vocabularyFor,
  makeLocaleMatcher,
  aiNounAlternation,
  _internal,
} from "../../src/rules/_i18n-vocabulary.js";

let dirs: string[] = [];
const savedEnv = process.env.LYSE_CONFIG_PATH;

function makeRepo(yaml?: string): string {
  const dir = mkdtempSync(join(tmpdir(), "lyse-i18n-"));
  if (yaml !== undefined) writeFileSync(join(dir, ".lyse.yaml"), yaml);
  dirs.push(dir);
  return dir;
}

beforeEach(() => {
  delete process.env.LYSE_CONFIG_PATH;
  _internal.clearVocabularyCache();
});

afterEach(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
  dirs = [];
  if (savedEnv === undefined) delete process.env.LYSE_CONFIG_PATH;
  else process.env.LYSE_CONFIG_PATH = savedEnv;
});

describe("BUILTIN_LOCALES", () => {
  it("exposes the five built-in locales", () => {
    expect(BUILTIN_LOCALES).toEqual(["en", "fr", "de", "ja", "es"]);
  });
});

describe("vocabularyFor", () => {
  it("returns all built-in aiNouns when no config exists", () => {
    const repo = makeRepo();
    const terms = vocabularyFor("aiNouns", repo);
    expect(terms).toContain("ai");
    expect(terms).toContain("ia");
    expect(terms).toContain("ki");
    expect(terms).toContain("人工知能");
  });

  it("returns built-ins only for empty repoRoot", () => {
    const terms = vocabularyFor("aiNouns", "");
    expect(terms).toContain("ai");
    expect(terms).toContain("人工知能");
  });

  it("restricts to active locales from .lyse.yaml", () => {
    const repo = makeRepo('i18n:\n  locales: ["en", "fr"]\n');
    const terms = vocabularyFor("aiNouns", repo);
    expect(terms).toContain("ai");
    expect(terms).toContain("ia");
    expect(terms).not.toContain("ki");
    expect(terms).not.toContain("人工知能");
  });

  it("excludes non-active locale phrases in other domains", () => {
    const repo = makeRepo('i18n:\n  locales: ["en"]\n');
    const terms = vocabularyFor("disclaimerPhrases", repo);
    expect(terms).toContain("generated by ai");
    expect(terms).not.toContain("généré par l'ia");
    expect(terms).not.toContain("ki-generiert");
  });

  it("merges user vocabulary additions into built-ins", () => {
    const repo = makeRepo(
      'i18n:\n  vocabulary:\n    aiNouns: ["xAI"]\n',
    );
    const terms = vocabularyFor("aiNouns", repo);
    expect(terms).toContain("xai");
    expect(terms).toContain("ai");
  });

  it("lowercases and dedupes user additions against built-ins", () => {
    const repo = makeRepo(
      'i18n:\n  vocabulary:\n    aiNouns: ["AI", "Ai"]\n',
    );
    const terms = vocabularyFor("aiNouns", repo);
    expect(terms.filter((t) => t === "ai")).toHaveLength(1);
  });

  it("returns sorted, deterministic output across calls", () => {
    const repo = makeRepo();
    const a = vocabularyFor("controlLabels", repo);
    const b = vocabularyFor("controlLabels", repo);
    expect(a).toEqual(b);
    expect(a).toEqual([...a].sort());
  });

  it("memoization does not leak across repoRoots", () => {
    const repoA = makeRepo('i18n:\n  locales: ["en"]\n');
    const repoB = makeRepo('i18n:\n  locales: ["fr"]\n');
    const a1 = vocabularyFor("aiNouns", repoA);
    const b = vocabularyFor("aiNouns", repoB);
    const a2 = vocabularyFor("aiNouns", repoA);
    expect(a1).toEqual(a2);
    expect(a1).toContain("ai");
    expect(a1).not.toContain("ia");
    expect(b).toContain("ia");
    expect(b).not.toContain("ai");
  });
});

describe("makeLocaleMatcher", () => {
  it("matchesPhrase finds a French disclaimer in copy text", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("disclaimerPhrases", repo);
    expect(matcher.matchesPhrase("Ce texte est généré par l'IA")).toBe(true);
  });

  it("matchesPhrase rejects normal sentences", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("disclaimerPhrases", repo);
    expect(matcher.matchesPhrase("just a normal sentence")).toBe(false);
  });

  it("matchesPhrase finds Japanese disclaimers", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("disclaimerPhrases", repo);
    expect(matcher.matchesPhrase("この内容は不正確な場合があります")).toBe(true);
  });

  it("matchesLabel matches a localized button label exactly (case/trim insensitive)", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("controlLabels", repo);
    expect(matcher.matchesLabel("Régénérer")).toBe(true);
    expect(matcher.matchesLabel("  Regenerate  ")).toBe(true);
    expect(matcher.matchesLabel("再生成")).toBe(true);
    expect(matcher.matchesLabel("Save")).toBe(false);
  });

  it("matchesLabel does not do substring matching", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("controlLabels", repo);
    expect(matcher.matchesLabel("Stop everything now please")).toBe(false);
  });

  it("has() checks exact term membership", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("aiNouns", repo);
    expect(matcher.has("AI")).toBe(true);
    expect(matcher.has("blockchain")).toBe(false);
  });

  it("terms reflects vocabularyFor output", () => {
    const repo = makeRepo();
    const matcher = makeLocaleMatcher("gatePhrases", repo);
    expect(matcher.terms).toEqual(vocabularyFor("gatePhrases", repo));
  });

  it("respects user vocabulary in matchers", () => {
    const repo = makeRepo(
      'i18n:\n  vocabulary:\n    controlLabels: ["Try harder"]\n',
    );
    const matcher = makeLocaleMatcher("controlLabels", repo);
    expect(matcher.matchesLabel("Try Harder")).toBe(true);
  });
});

describe("aiNounAlternation", () => {
  it("returns a regex-safe alternation of all active nouns", () => {
    const repo = makeRepo();
    const alternation = aiNounAlternation(repo);
    const re = new RegExp(`(?:${alternation})`, "iu");
    expect(re.test("AI")).toBe(true);
    expect(re.test("人工知能")).toBe(true);
  });

  it("escapes user terms with regex metacharacters", () => {
    const repo = makeRepo(
      'i18n:\n  vocabulary:\n    aiNouns: ["a.i"]\n',
    );
    const alternation = aiNounAlternation(repo);
    const re = new RegExp(`^(?:${alternation})$`, "iu");
    expect(re.test("a.i")).toBe(true);
    expect(re.test("aXi")).toBe(false);
  });

  it("orders longer terms first so alternation prefers the longest match", () => {
    const repo = makeRepo('i18n:\n  vocabulary:\n    aiNouns: ["aix"]\n');
    const alternation = aiNounAlternation(repo);
    const re = new RegExp(`(?:${alternation})`, "iu");
    expect("aix".match(re)?.[0]).toBe("aix");
  });
});
