import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  rule,
  _internal,
} from "../../src/rules/ai-governance-disclaimer-present.js";
import type { RuleContext, ParsedFiles } from "../../src/types.js";

const { detectDisclaimer, detectAiMarkerInSource } = _internal;

const emptyParsed: ParsedFiles = { ts: [], css: [], cssInJs: [] };

function makeCtx(repoRoot: string): RuleContext {
  return {
    repoRoot,
    tokens: null,
    componentsModule: null,
    componentInventory: [],
    storyIndex: null,
    excludePaths: [],
  };
}

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "lyse-disclaimer-"));
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Unit: detectDisclaimer
// ---------------------------------------------------------------------------

describe("detectDisclaimer", () => {
  it("detects 'Generated by AI' text (case-insensitive)", () => {
    const result = detectDisclaimer(`<p>Generated by AI</p>`);
    expect(result.found).toBe(true);
    expect(result.isGitLabExact).toBe(false);
  });

  it("detects 'AI-generated' hyphenated variant", () => {
    expect(detectDisclaimer(`<span>AI-generated content</span>`).found).toBe(true);
  });

  it("detects 'May be inaccurate' phrase", () => {
    expect(detectDisclaimer(`<p>May be inaccurate. Please verify.</p>`).found).toBe(true);
  });

  it("detects 'Check important info' phrase", () => {
    expect(detectDisclaimer(`<div>Check important info before acting.</div>`).found).toBe(true);
  });

  it("detects 'Powered by AI' phrase", () => {
    expect(detectDisclaimer(`Powered by AI`).found).toBe(true);
  });

  it("detects <AIDisclaimer/> component", () => {
    expect(detectDisclaimer(`<AIDisclaimer />`).found).toBe(true);
  });

  it("detects any *Disclaimer* component tag", () => {
    expect(detectDisclaimer(`<GenerativeDisclaimer message="..." />`).found).toBe(true);
  });

  it("sets isGitLabExact=true for the GitLab Pajamas canonical disclaimer wording", () => {
    const GITLAB_EXACT_DISCLAIMER =
      "AI-generated content may be inaccurate. Always check important information.";
    const result = detectDisclaimer(GITLAB_EXACT_DISCLAIMER);
    expect(result.found).toBe(true);
    expect(result.isGitLabExact).toBe(true);
  });

  it("returns found=false when no disclaimer signal is present", () => {
    expect(detectDisclaimer(`<Button>Summarize</Button>`).found).toBe(false);
  });

  it("does not match 'ai' within other words (detail, main)", () => {
    expect(detectDisclaimer(`<p>Detail and main content.</p>`).found).toBe(false);
  });

  it("detects lowercase 'generated by ai'", () => {
    expect(detectDisclaimer(`generated by ai`).found).toBe(true);
  });

  it("detects 'ai generated' (space variant)", () => {
    expect(detectDisclaimer(`<p>AI generated text</p>`).found).toBe(true);
  });

  it("detects 'Disclaimer' component name (generic)", () => {
    expect(detectDisclaimer(`<Disclaimer />`).found).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Unit: detectAiMarkerInSource
// ---------------------------------------------------------------------------

describe("detectAiMarkerInSource", () => {
  it("detects an AILabel component tag as an AI marker", () => {
    expect(detectAiMarkerInSource(`<AILabel />`)).toBe(true);
  });

  it("detects Polaris magic-* component as an AI marker", () => {
    expect(detectAiMarkerInSource(`<magic-icon />`)).toBe(true);
  });

  it("detects AIBadge component as an AI marker", () => {
    expect(detectAiMarkerInSource(`<AIBadge label="AI" />`)).toBe(true);
  });

  it("returns false when no AI-marker component is present", () => {
    expect(detectAiMarkerInSource(`<Button>Submit</Button>`)).toBe(false);
  });

  it("detects GenAI* variant", () => {
    expect(detectAiMarkerInSource(`<GenAIBadge />`)).toBe(true);
  });

  it("detects AITag component", () => {
    expect(detectAiMarkerInSource(`<AITag />`)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Integration: rule.create().evaluate
// ---------------------------------------------------------------------------

describe("rule.evaluate — integration", () => {
  it("emits warning when AI-marker component present but no disclaimer found", async () => {
    writeFileSync(
      join(tmp, "AISummary.tsx"),
      `
      import { AILabel } from "@ds/ai";
      export function AISummary({ text }: { text: string }) {
        return <div><AILabel /><p>{text}</p></div>;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("warning");
    expect(result.findings[0]?.message).toMatch(/HAX G1/);
  });

  it("emits info when AI-marker and 'Generated by AI' disclaimer text are present", async () => {
    writeFileSync(
      join(tmp, "AISummary.tsx"),
      `
      export function AISummary({ text }: { text: string }) {
        return <div><AILabel /><p>{text}</p><p>Generated by AI</p></div>;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("info");
    expect(result.findings[0]?.message).not.toMatch(/GitLab/);
  });

  it("emits info noting GitLab canonical match when AI-marker and exact Pajamas string are present", async () => {
    const GITLAB_EXACT =
      "AI-generated content may be inaccurate. Always check important information.";
    writeFileSync(
      join(tmp, "AICard.tsx"),
      `
      export function AICard() {
        return <div><AILabel /><p>${GITLAB_EXACT}</p></div>;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("info");
    expect(result.findings[0]?.message).toMatch(/GitLab/);
  });

  it("emits info when AI-marker and AIDisclaimer component are co-located", async () => {
    writeFileSync(
      join(tmp, "AISummary.tsx"),
      `
      import { AILabel, AIDisclaimer } from "@ds/ai";
      export function AISummary() {
        return <div><AILabel /><AIDisclaimer /></div>;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("info");
  });

  it("emits no finding when no AI marker and no disclaimer present", async () => {
    writeFileSync(
      join(tmp, "Button.tsx"),
      `
      export function Button({ label }: { label: string }) {
        return <button>{label}</button>;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("emits no finding for a CookieDisclaimer component with no AI marker (no false AI-surface)", async () => {
    writeFileSync(
      join(tmp, "CookieBanner.tsx"),
      `
      import { CookieDisclaimer } from "@legal/cookies";
      export function CookieBanner() {
        return <CookieDisclaimer message="We use cookies." />;
      }
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("emits warning for a Vue SFC with AI-marker and no disclaimer", async () => {
    writeFileSync(
      join(tmp, "AIOutput.vue"),
      `
      <template>
        <div>
          <AIBadge />
          <p>{{ content }}</p>
        </div>
      </template>
      <script setup lang="ts">
      defineProps<{ content: string }>();
      </script>
    `,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("warning");
  });

  it("emits no finding when repo is allowlisted via README", async () => {
    writeFileSync(
      join(tmp, "AISummary.tsx"),
      `export function AISummary() { return <AILabel />; }`,
    );
    writeFileSync(
      join(tmp, "README.md"),
      "lyse-disable ai-governance/disclaimer-present\n",
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("emits no finding when repoRoot is missing", async () => {
    const ctx: RuleContext = {
      repoRoot: "",
      tokens: null,
      componentsModule: null,
      componentInventory: [],
      storyIndex: null,
      excludePaths: [],
    };
    const result = await rule.evaluate(ctx, emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("findings are sorted by file path (deterministic output)", async () => {
    writeFileSync(
      join(tmp, "ZComp.tsx"),
      `export function ZComp() { return <AILabel />; }`,
    );
    writeFileSync(
      join(tmp, "AComp.tsx"),
      `export function AComp() { return <AIBadge />; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings.length).toBeGreaterThanOrEqual(2);
    const files = result.findings.map((f) => f.location?.file ?? "");
    expect(files).toEqual([...files].sort());
  });
});
