import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  rule,
  hasDraftAttribution,
} from "../../src/rules/ai-governance-draft-attribution.js";
import type { RuleContext, ParsedFiles } from "../../src/types.js";

const emptyParsed: ParsedFiles = { ts: [], css: [], cssInJs: [] };
function makeCtx(repoRoot: string): RuleContext {
  return { repoRoot, tokens: null, componentsModule: null, componentInventory: [], storyIndex: null, excludePaths: [] };
}

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "lyse-draft-attr-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

describe("hasDraftAttribution", () => {
  it("matches the 'first draft created/generated with/by [tool]' convention", () => {
    expect(hasDraftAttribution("First draft created with Claude")).toBe(true);
    expect(hasDraftAttribution("This first draft was generated by an AI assistant.")).toBe(true);
    expect(hasDraftAttribution("first draft drafted with Copilot")).toBe(true);
  });
  it("matches structured attribution markers", () => {
    expect(hasDraftAttribution('<Card data-ai-generated="true" />')).toBe(true);
    expect(hasDraftAttribution("export const DraftAttribution = () => null;")).toBe(true);
    expect(hasDraftAttribution("const meta = { aiGenerated: true };")).toBe(true);
  });
  it("does NOT match generic 'created with' / unrelated 'first draft' text", () => {
    expect(hasDraftAttribution("Created with Sketch")).toBe(false);
    expect(hasDraftAttribution("Made with love")).toBe(false);
    expect(hasDraftAttribution("This is the first draft of the proposal.")).toBe(false);
  });
});

describe("rule ai-governance/draft-attribution", () => {
  it("emits info when an AI surface exists and the attribution convention is present", async () => {
    mkdirSync(join(tmp, "src"), { recursive: true });
    writeFileSync(join(tmp, "src", "AILabel.tsx"), "export const AILabel = () => null;");
    writeFileSync(join(tmp, "README.md"), "# DS\n\nFirst draft created with Claude. Reviewed by the team.\n");
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    const f = result.findings[0]!;
    expect(f.severity).toBe("info");
    expect(f.axis).toBe("ai-governance");
    expect(f.ruleId).toBe("ai-governance/draft-attribution");
  });

  it("emits warning when an AI surface exists but no attribution convention is present", async () => {
    mkdirSync(join(tmp, "src"), { recursive: true });
    writeFileSync(join(tmp, "src", "AILabel.tsx"), "export const AILabel = () => null;");
    writeFileSync(join(tmp, "README.md"), "# DS\n\n## Installation\n");
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]!.severity).toBe("warning");
  });

  it("emits no finding when there is no AI surface", async () => {
    mkdirSync(join(tmp, "src"), { recursive: true });
    writeFileSync(join(tmp, "src", "Button.tsx"), "export const Button = () => null;");
    writeFileSync(join(tmp, "README.md"), "First draft created with Claude.\n");
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("returns no findings when repoRoot is not set", async () => {
    const result = await rule.evaluate(makeCtx(""), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("emits no finding when README.md contains the lyse-disable directive", async () => {
    mkdirSync(join(tmp, "src"), { recursive: true });
    writeFileSync(join(tmp, "src", "AILabel.tsx"), "export const AILabel = () => null;");
    writeFileSync(join(tmp, "README.md"), "<!-- lyse-disable ai-governance/draft-attribution -->\n");
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });
});
