import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { _internal, rule } from "../../src/rules/ai-governance-ai-marker-anti-patterns.js";
import type { RuleContext, ParsedFiles } from "../../src/types.js";

const { detectSparkleOnlyMarker, detectAiInCtaLabel } = _internal;

const emptyParsed: ParsedFiles = { ts: [], css: [], cssInJs: [] };

function makeCtx(repoRoot: string): RuleContext {
  return {
    repoRoot,
    tokens: null,
    componentsModule: null,
    componentInventory: [],
    storyIndex: null,
    excludePaths: [],
  };
}

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "lyse-ai-marker-ap-"));
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Unit: detectSparkleOnlyMarker
// ---------------------------------------------------------------------------
describe("detectSparkleOnlyMarker", () => {
  it("flags ✨ literal with no text marker", () => {
    expect(detectSparkleOnlyMarker(`<span>✨ {summary}</span>`)).toBe(true);
  });

  it("flags Sparkles icon import used without text marker", () => {
    expect(
      detectSparkleOnlyMarker(
        `import { Sparkles } from "lucide-react";\n<Sparkles/>`,
      ),
    ).toBe(true);
  });

  it("flags Sparkle (singular) icon import without text marker", () => {
    expect(
      detectSparkleOnlyMarker(`import { Sparkle } from "lucide-react";\n<p>hello</p>`),
    ).toBe(true);
  });

  it("flags SparkleIcon import without text marker", () => {
    expect(
      detectSparkleOnlyMarker(`import { SparkleIcon } from "@radix-ui/react-icons";\n<SparkleIcon/>`),
    ).toBe(true);
  });

  it("does NOT flag sparkle accompanied by a text AI marker (AI_MARKER_NAMES component)", () => {
    expect(
      detectSparkleOnlyMarker(`<AILabel/> <Sparkles/>`),
    ).toBe(false);
  });

  it("does NOT flag sparkle accompanied by 'Generated by AI' text", () => {
    expect(
      detectSparkleOnlyMarker(`✨ <span>Generated by AI</span>`),
    ).toBe(false);
  });

  it("does NOT flag sparkle accompanied by 'AI-generated' text", () => {
    expect(
      detectSparkleOnlyMarker(`✨ AI-generated content`),
    ).toBe(false);
  });

  it("does NOT flag sparkle accompanied by 'Powered by AI' text", () => {
    expect(
      detectSparkleOnlyMarker(`✨ Powered by AI`),
    ).toBe(false);
  });

  it("does NOT flag a file with no sparkle at all", () => {
    expect(detectSparkleOnlyMarker(`<button>Summarize</button>`)).toBe(false);
  });

  it("does NOT flag magic-* component (Polaris) — it IS a text marker", () => {
    expect(
      detectSparkleOnlyMarker(`<magic-icon/> ✨`),
    ).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Unit: detectAiInCtaLabel
// ---------------------------------------------------------------------------
describe("detectAiInCtaLabel", () => {
  it("flags a button whose label is exactly AI", () => {
    expect(detectAiInCtaLabel(`<Button>AI</Button>`)).toEqual([{ label: "AI" }]);
  });

  it("flags a button whose label is an AI action (Ask AI)", () => {
    expect(detectAiInCtaLabel(`<button>Ask AI</button>`)).toEqual([{ label: "Ask AI" }]);
  });

  it("flags multiple buttons with AI in their labels", () => {
    const result = detectAiInCtaLabel(
      `<button>Ask AI</button>\n<button>Summarize</button>\n<button>AI</button>`,
    );
    expect(result).toHaveLength(2);
    expect(result[0]).toEqual({ label: "Ask AI" });
    expect(result[1]).toEqual({ label: "AI" });
  });

  it("does NOT flag 'AI' in non-CTA text (heading)", () => {
    expect(detectAiInCtaLabel(`<h2>AI suggestions</h2>`)).toEqual([]);
  });

  it("does NOT flag words merely containing the letters ai (case-sensitive)", () => {
    expect(detectAiInCtaLabel(`<button>Train model</button>`)).toEqual([]);
    expect(detectAiInCtaLabel(`<button>Maintain</button>`)).toEqual([]);
  });

  it("does NOT flag 'ai' in lowercase inside a button", () => {
    expect(detectAiInCtaLabel(`<button>ai assistant</button>`)).toEqual([]);
  });

  it("flags an anchor link styled as a button with AI label", () => {
    expect(detectAiInCtaLabel(`<a>AI</a>`)).toEqual([{ label: "AI" }]);
  });

  it("does NOT flag an empty button", () => {
    expect(detectAiInCtaLabel(`<button></button>`)).toEqual([]);
  });

  it("flags role=\"button\" element with standalone AI label", () => {
    expect(detectAiInCtaLabel(`<div role="button">Ask AI</div>`)).toEqual([{ label: "Ask AI" }]);
  });

  it("flags role=\'button\' (single-quoted) element with AI label", () => {
    expect(detectAiInCtaLabel(`<span role='button'>AI</span>`)).toEqual([{ label: "AI" }]);
  });
});

// ---------------------------------------------------------------------------
// Unit: localized anti-patterns (Track 9.1)
// ---------------------------------------------------------------------------
describe("localized anti-patterns (Track 9.1)", () => {
  it("does NOT flag sparkle accompanied by 'Généré par IA' (fr)", () => {
    expect(detectSparkleOnlyMarker(`✨ <span>Généré par IA</span>`)).toBe(false);
  });

  it("does NOT flag sparkle accompanied by standalone 'KI' text (de)", () => {
    expect(detectSparkleOnlyMarker(`✨ <span>Von KI erstellt</span>`)).toBe(false);
  });

  it("flags <button>IA</button> as an AI-CTA anti-pattern (fr)", () => {
    expect(detectAiInCtaLabel(`<button>IA</button>`)).toEqual([{ label: "IA" }]);
  });

  it("flags <button>KI</button> as an AI-CTA anti-pattern (de)", () => {
    expect(detectAiInCtaLabel(`<button>KI</button>`)).toEqual([{ label: "KI" }]);
  });

  it("still flags <button>AI</button> (regression)", () => {
    expect(detectAiInCtaLabel(`<button>AI</button>`)).toEqual([{ label: "AI" }]);
  });

  it("does NOT flag a normal <button>Save</button>", () => {
    expect(detectAiInCtaLabel(`<button>Save</button>`)).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Integration: rule.evaluate
// ---------------------------------------------------------------------------
describe("rule.evaluate — integration", () => {
  it("sparkle-only .tsx with no AI context → 0 findings (decorative sparkle is not flagged)", async () => {
    writeFileSync(
      join(tmp, "Summary.tsx"),
      `export function Summary() { return <span>✨ {text}</span>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("AI marker component exporting AI name + sparkle sole marker → 1 warning (SAP Fiori)", async () => {
    writeFileSync(
      join(tmp, "AIBadge.tsx"),
      `export function AIBadge() { return <span>✨</span>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("warning");
    expect(result.findings[0]?.message).toContain("SAP Fiori");
  });

  it("<button>Ask AI</button> → 1 warning, message contains GitLab", async () => {
    writeFileSync(
      join(tmp, "Actions.tsx"),
      `export function Actions() { return <button>Ask AI</button>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("warning");
    expect(result.findings[0]?.message).toContain("GitLab");
  });

  it("FR component: BadgeIA marker + sparkle + 'Généré par IA' → 0 findings (Track 9.1)", async () => {
    writeFileSync(
      join(tmp, "BadgeIA.tsx"),
      `export function BadgeIA() { return <span>✨ Généré par IA</span>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("FR CTA <button>IA</button> → 1 warning, message contains GitLab (Track 9.1)", async () => {
    writeFileSync(
      join(tmp, "Actions.tsx"),
      `export function Actions() { return <button>IA</button>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.severity).toBe("warning");
    expect(result.findings[0]?.message).toContain("GitLab");
  });

  it("sparkle + <AILabel/> → 0 findings", async () => {
    writeFileSync(
      join(tmp, "Safe.tsx"),
      `export function Safe() { return <><AILabel/><span>✨</span></>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("<h2>AI suggestions</h2> only → 0 findings", async () => {
    writeFileSync(
      join(tmp, "Heading.tsx"),
      `export function Heading() { return <h2>AI suggestions</h2>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("Vue SFC sparkle-only with no AI context → 0 findings", async () => {
    writeFileSync(
      join(tmp, "Summary.vue"),
      `<template><span>✨ {{ summary }}</span></template>`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("README with lyse-disable → 0 findings (allowlist)", async () => {
    writeFileSync(
      join(tmp, "Badge.tsx"),
      `export function Badge() { return <span>✨</span>; }`,
    );
    writeFileSync(
      join(tmp, "README.md"),
      `lyse-disable ai-governance/ai-marker-anti-patterns`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("empty repo → 0 findings, opportunities: 0", async () => {
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("jsx file with sparkle-only and no AI context → 0 findings", async () => {
    writeFileSync(
      join(tmp, "Icon.jsx"),
      `import { Sparkles } from "lucide-react";\nexport function Icon() { return <Sparkles/>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("CTA file with AI label + separate sparkle-only file without AI context → 1 CTA warning only", async () => {
    writeFileSync(
      join(tmp, "CTA.tsx"),
      `export function CTA() { return <button>Ask AI</button>; }`,
    );
    writeFileSync(
      join(tmp, "Sparkle.tsx"),
      `export function Sparkle() { return <span>✨ summary</span>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    const ctaFindings = result.findings.filter((f) => f.message.includes("GitLab"));
    const sparkleFindings = result.findings.filter((f) => f.message.includes("SAP Fiori"));
    expect(ctaFindings).toHaveLength(1);
    expect(sparkleFindings).toHaveLength(0);
    expect(result.findings).toHaveLength(1);
  });

  it("opportunities equals number of component files scanned", async () => {
    writeFileSync(join(tmp, "A.tsx"), `export function A() { return <div/>; }`);
    writeFileSync(join(tmp, "B.tsx"), `export function B() { return <div/>; }`);
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.opportunities).toBe(2);
  });

  it("no repoRoot → 0 findings, opportunities: 0", async () => {
    const ctx: RuleContext = {
      repoRoot: undefined,
      tokens: null,
      componentsModule: null,
      componentInventory: [],
      storyIndex: null,
      excludePaths: [],
    };
    const result = await rule.evaluate(ctx, emptyParsed);
    expect(result.findings).toHaveLength(0);
    expect(result.opportunities).toBe(0);
  });

  it("regression: file with sparkle + CTA AI label but no AI context → only 1 CTA warning (B), no sparkle warning", async () => {
    writeFileSync(
      join(tmp, "Mixed.tsx"),
      `export function Mixed() {
  return (
    <div>
      <span>✨ {summary}</span>
      <button>Ask AI</button>
    </div>
  );
}`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    const sparkleFindings = result.findings.filter((f) => f.message.includes("SAP Fiori"));
    const ctaFindings = result.findings.filter((f) => f.message.includes("GitLab"));
    expect(sparkleFindings).toHaveLength(0);
    expect(ctaFindings).toHaveLength(1);
    expect(result.findings).toHaveLength(1);
  });

  it("regression: HeroBanner with decorative sparkle and no AI context → 0 findings", async () => {
    writeFileSync(
      join(tmp, "HeroBanner.tsx"),
      `export function HeroBanner() { return <div>✨ Welcome!</div>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    expect(result.findings).toHaveLength(0);
  });

  it("role=\"button\" element with AI label → 1 CTA warning", async () => {
    writeFileSync(
      join(tmp, "RoleButton.tsx"),
      `export function RoleButton() { return <div role="button">Ask AI</div>; }`,
    );
    const result = await rule.evaluate(makeCtx(tmp), emptyParsed);
    const ctaFindings = result.findings.filter((f) => f.message.includes("GitLab"));
    expect(ctaFindings).toHaveLength(1);
  });
});
